# Generated by Django 3.1 on 2020-09-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200910_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='dob',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='dod',
            field=models.DateField(max_length=50),
        ),
    ]
