# Generated by Django 3.1 on 2020-09-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200910_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeding date')),
                ('care', models.CharField(choices=[('O', 'Oral Hygiene'), ('F', 'Foot Care'), ('E', 'Exercise')], default='O', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='elephant',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='elephant',
            name='dod',
        ),
        migrations.AddField(
            model_name='elephant',
            name='birthdate',
            field=models.CharField(choices=[('U', 'Unknown'), ('D', 'YYYY')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='elephant',
            name='died',
            field=models.CharField(choices=[('U', ''), ('D', 'YYYY'), ('A', 'Alive')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
