# Generated by Django 3.1 on 2020-09-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200912_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='date',
            field=models.DateField(verbose_name='care date'),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='died',
            field=models.CharField(choices=[('U', 'Unknown'), ('D', 'YYYY'), ('A', 'Alive')], default='U', max_length=1),
        ),
    ]
