# Generated by Django 3.1 on 2020-09-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200912_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='note',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='wikilink',
            field=models.URLField(),
        ),
    ]
