# Generated by Django 3.1 on 2020-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_care_elephant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elephant',
            name='fictional',
        ),
        migrations.AlterField(
            model_name='elephant',
            name='birthdate',
            field=models.CharField(choices=[('U', 'Unknown'), ('D', 'Year')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='died',
            field=models.CharField(choices=[('U', 'Unknown'), ('D', 'Year'), ('A', 'Alive')], default='U', max_length=1),
        ),
    ]
