# Generated by Django 3.1 on 2020-09-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200912_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='birthdate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='died',
            field=models.CharField(max_length=50),
        ),
    ]
