# Generated by Django 3.1 on 2020-09-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200913_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='care',
            old_name='care',
            new_name='service',
        ),
    ]
