# Generated by Django 3.1 on 2020-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200913_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='care',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='care',
            name='service',
            field=models.CharField(choices=[('O', 'Oral Hygiene'), ('F', 'Checked Feet'), ('E', 'Exercise')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='elephant',
            name='trainer',
            field=models.ManyToManyField(to='main_app.Trainer'),
        ),
    ]
