# Generated by Django 3.1 on 2020-09-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200913_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elephant',
            old_name='trainer',
            new_name='trainers',
        ),
    ]
