# Generated by Django 3.1 on 2020-09-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200913_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('elephant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.elephant')),
            ],
        ),
    ]
