# Generated by Django 3.1 on 2020-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_elephant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='birthdate',
            field=models.CharField(help_text="Enter the Elephant's Birth Year or Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='died',
            field=models.CharField(help_text='Enter the Year the Elephant Died, Unknown or Alive', max_length=50),
        ),
    ]
