# Generated by Django 3.1.1 on 2020-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200913_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elephant',
            name='image',
        ),
        migrations.AlterField(
            model_name='elephant',
            name='birthdate',
            field=models.CharField(help_text="Please enter the Elephant's Birth Year or 'Unknown'", max_length=50),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='died',
            field=models.CharField(help_text="Please enter the Year the Elephant Died, 'Unknown' or 'Alive'", max_length=50),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='species',
            field=models.CharField(choices=[('1', 'African'), ('2', 'Asian')], default='1', max_length=1),
        ),
    ]
