# Generated by Django 3.1.1 on 2020-09-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200924_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephant',
            name='affiliation',
            field=models.CharField(help_text='Please Enter the Person or Company with whom they were most Affiated.', max_length=200),
        ),
    ]
