# Generated by Django 3.1.1 on 2020-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200924_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='elephant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
