# Generated by Django 3.1.1 on 2020-09-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20200924_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elephant',
            options={'ordering': ['name']},
        ),
    ]
