# Generated by Django 3.1.1 on 2020-09-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20200924_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
    ]
